const CarMakes=[
    {
        id:1,
        name:'Audi'
    },
    {
        id:2,
        name:'BMW'
    },
    {
        id:3,
        name:'Mercedes'
    },
    {
        id:4,
        name:'Volkswagen'
    },
    {
        id:5,
        name:'Ford'
    },
    {
        id:6,
        name:'Chevrolet'
    },
    {
        id:7,
        name:'Toyota'
    },
    {
        id:8,
        name:'Honda'
    },
    {
        id:9,
        name:'Nissan'
    },
    {
        id:10,
        name:'Hyundai'
    }

]

const Pricing=[
    {
        id:1,
        amount:'$1000',
    },
    {
        id:2,
        amount:'$2000',
    },
    {
        id:3,
        amount:'$3000',
    },
    {
        id:4,
        amount:'$4000',
    },
    {
        id:5,
        amount:'$5000',
    },
    {
        id:6,
        amount:'$6000',
    },
    {
        id:7,
        amount:'$7000',
    },
    {
        id:8,
        amount:'$8000',
    },
    {
        id:9,
        amount:'$9000',
    },
    {
        id:10,
        amount:'$10000',
    }
]

const Category=[
    {
        id:1,
        name:'SUV',
        icon:'https://cdn-icons-png.flaticon.com/128/13584/13584003.png'
    },
    {
        id:2,
        name:'Sedan',
        icon:'https://cdn-icons-png.flaticon.com/128/3202/3202003.png'
    },
    {
        id:3,
        name:'Hatchback',
        icon:'https://cdn-icons-png.flaticon.com/128/5035/5035167.png'
    },
    {
        id:4,
        name:'Electric',
        icon:'https://cdn-icons-png.flaticon.com/128/4564/4564336.png'
    },
    {
        id:5,
        name:'Convertible',
        icon:'https://cdn-icons-png.flaticon.com/128/5035/5035202.png'
    },
    {
        id:5,
        name:'Hybrid',
        icon:'https://cdn-icons-png.flaticon.com/128/3202/3202003.png'
    },
    {
        id:5,
        name:'Coupe',
        icon:'https://cdn-icons-png.flaticon.com/128/4391/4391630.png'
    },
    {
        id:5,
        name:'Van',
        icon:'https://cdn-icons-png.flaticon.com/128/1433/1433678.png'
    },
    {
        id:5,
        name:'Truck',
        icon:'https://cdn-icons-png.flaticon.com/128/5814/5814855.png'
    },
 
    
]

export default{
    CarMakes,
    Pricing,
    Category
}